version: '3'

services:
  tab-extension-backend:
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - 80:3000
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - tab-extension-network
  db:
    image: mongo:6.0.5
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/mongo/data/db:/data/db
    networks:
      - tab-extension-network

networks:
  tab-extension-network:
    driver: bridge
